# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            anonymous: ~
            provider: our_db_provider
            logout: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: admin_login
                check_path: _admin_login_check
                default_target_path: admin_post

        source_area:
            form_login:
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt